language: python
python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
script:
- pytest -m app.api.v1.auth.tests.test_auth
- pytest -m app.api.v1.question.test.test_questions
  

