language: python
python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
script:
- coverage run --source= app -m app.api.v1.auth.tests.test_auth
- coverage run --source= app -m app.api.v1.auth.tests.test_auth
  

