language: python
python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install pytest
script:
- pytest app.api.v1.auth.tests.test_auth.py
- pytest app.api.v1.question.test.test_questions.py
  

